import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: {
  children: React.ReactNode
}): React.JSX.Element => {
  return (
    <html lang="es">
      <body className={
        cn(
          'min-h-screen',
          inter.className,
          'bg-[url("/background.png")] bg-cover bg-no-repeat bg-center bg-fixed backdrop-blur-md'
        )
      }>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
